#!/bin/bash

PUSH=0

while getopts ":p" OPTION; do
    case $OPTION in
    p)
        PUSH=1
        shift 1;
        ;;
    *)
        echo "Incorrect options provided"
        exit 1
        ;;
    esac
done

TYPE=$1
VER=$2

set -e

if [ $PUSH == 0 ];
then
  echo "Push disabled...";
else
  echo "Push enabled...";
fi;

if [ -z "$TYPE" ]
then
  echo "Usage: $0 type [version]"
  exit 1;
fi

function build {
  echo "[$2] Building image...";

  date=$(date '+%Y%m%d')

  if docker buildx build "$1" --tag "$2" --tag "${2}-${date}";
  then
    if [ $PUSH == 1 ];
    then
      echo "[$2] Pushing image...";
      docker buildx build "$1" --tag "$2" --tag "${2}-${date}" --platform linux/arm64/v8,linux/amd64 --push
    fi
  fi
}

if [ -z "$VER" ]
then
  for dir in "$TYPE"/*; do
    tag="szainmehdi/$(echo "$dir" | tr '/' ':')"; \
    build "$dir" "$tag";
  done;
else
  tag="szainmehdi/$TYPE:$VER";
  build "$TYPE/$VER" "$tag"
fi

echo "Done!"
