#!/bin/bash
TYPE=$1
VER=$2

if [ -z "$TYPE" ]
then
  echo "Usage: $0 type [version]"
  exit 1;
fi

if [ -z "$VER" ]
then
  for dir in "$TYPE"/*; do
    tag="szainmehdi/$(echo "$dir" | tr '/' ':')"; \
    echo "[$tag] Building image..."; \
    docker build "$dir" --tag "$tag" \
      && docker push "$tag";
  done;
else
  tag="szainmehdi/$TYPE:$VER";
  echo "[$tag] Building image...";
  docker build "$TYPE/$VER" --tag "$tag" \
      && docker push "$tag";
fi
